# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: AdvancedSecurity-Codeql-Init@1
  inputs:
    languages: 'python'

- task: AdvancedSecurity-Codeql-Autobuild@1

- task: AdvancedSecurity-Codeql-Analyze@1
  inputs:
    querysuite: 'security-and-quality'

- task: AdvancedSecurity-Publish@1

- task: AdvancedSecurity-Dependency-Scanning@1